### ISSUE TITLE
list-cookie-jar% fails to replace existing cookies, grows without bound

### ISSUE THREAD

**Issue by lexi-lambda** [RenaissanceBug/racket-cookies#14]
This program illustrates the issue:

```racket
#lang racket/base
(require net/cookies/user-agent
         net/url
         racket/class)

(define headers '(#"set-cookie: cookie1=value1; Max-Age=100000; path=/; httponly"
                  #"set-cookie: cookie2=value2; Max-Age=100000; path=/; httponly"))
(define url (string->url "https://example.com/"))

(extract-and-save-cookies! headers url)
(sleep 1)
(extract-and-save-cookies! headers url)
(sleep 1)
(extract-and-save-cookies! headers url)
(sleep 1)
(extract-and-save-cookies! headers url)

(send (current-cookie-jar) cookies-matching url)
```

This is the output of the above program:

```
(list (ua-cookie "cookie2" "value2" "example.com" "/" 1679995660 1679895660 1679895660 #t #t #f #t)
      (ua-cookie "cookie1" "value1" "example.com" "/" 1679995661 1679895660 1679895661 #t #t #f #t)
      (ua-cookie "cookie2" "value2" "example.com" "/" 1679995662 1679895661 1679895662 #t #t #f #t)
      (ua-cookie "cookie1" "value1" "example.com" "/" 1679995663 1679895662 1679895663 #t #t #f #t)
      (ua-cookie "cookie2" "value2" "example.com" "/" 1679995663 1679895663 1679895663 #t #t #f #t))
```

This is obviously not correct: there should only be two cookies in the jar, not five.

**Comment by RenaissanceBug** [comment]
Thanks! I'll take care of this today.

**Comment by RenaissanceBug** [comment]
Diagnosed the problem but got into some yak-shaving. Need to think about where to draw the line between _minimal bugfix_ and _rewriting I'll do in a separate branch afterwards_. Gonna sleep on it.

When I get done with this, do I have your permission to incorporate your example in ```net-cookies-test``` as a test, under the Apache2/MIT licensing terms already in place for this repo?

**Comment by lexi-lambda** [comment]
> When I get done with this, do I have your permission to incorporate your example in `net-cookies-test` as a test, under the Apache2/MIT licensing terms already in place for this repo?

Yes.

**Comment by RenaissanceBug** [comment]
OK, done. More changes coming soon as a result. Thanks for the bug report!
