### ISSUE TITLE
Test failure with quoting

### ISSUE THREAD

**Issue by samth** [RenaissanceBug/racket-cookies#8]
Currently, one of the tests in this package fails: http://drdr.racket-lang.org/39296/racket/share/pkgs/net-cookies-test/tests/net/cookies/server.rkt

```
cookie-header-parsing-tests > parse to alist: 3 cookies, 1 empty, 1 w/escaped dquotes
parse to alist: 3 cookies, 1 empty, 1 w/escaped dquotes
FAILURE
name:       check-equal?
location:   server.rkt:153:2
actual:     '((#"seenIntro" . #"") (#"uname" . #"bob") (#"nick" . #"FuzzyDucky"))
expected:   '((#"seenIntro" . #"") (#"uname" . #"bob") (#"nick" . #"\"FuzzyDucky\""))
Check failure
```

This may be related to #7 but I haven't investigated.

**Comment by samth** [comment]
cc @jeapostrophe

**Comment by RenaissanceBug** [comment]
AFAICT this was just that one test failing, as a result of @LiberalArtist correcting the library's handling of the Cookie: header. I've edited the test, so we should be OK now; let me know if you see anything still amiss.
