### ISSUE TITLE
times off by 1 second in some tests

### ISSUE THREAD

**Issue by samth** [RenaissanceBug/racket-cookies#9]
See for example http://drdr.racket-lang.org/47675/racket/share/pkgs/net-cookies-test/tests/net/cookies/user-agent.rkt

This is in the first of the `extract-cookies-test` test suite. Should this use `ua-cookie-matches?` from that file to be flexible about those times?

**Comment by RenaissanceBug** [comment]
Thanks for the report, Sam. I’m in the process of moving right now, but if Jay and his people haven’t addressed this by the time I’m in my new home next week, I will deal with it then.

I’ll need a little time to page in all the details again, but ua-cookie-matches is probably the right approach.

Jordan

**Comment by RenaissanceBug** [comment]
"Next week", I said, ever the optimist. Oh well. :)

Commit 505c9d78313b036b1b64a3cb948810eca5c718a5 should fix it. I've tested in DrRacket, but will let the next round of automated tests go through before closing the issue.

If I was originally correct, test failures should've been pretty darn rare already; it's conceivable that one or two could *still* fail, but even more unlikely, with a tolerance window of +/- a couple seconds.

**Comment by RenaissanceBug** [comment]
Closing this one now. Please do ping me again if you see the tests failing again — I may not notice otherwise.
